apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: westport-hpa
  labels:
    app: westport
    version: 0.0.1
    backstage.io/kubernetes-id: westport
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: westport
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75